'use strict';
const $=id=>document.getElementById(id);
const queue=[];let busy=false,stop=false,activeWorker=null,activeReject=null;
const size=n=>n<1048576?(n/1024).toFixed(0)+' KB':(n/1048576).toFixed(1)+' MB';
function announce(msg){$('status').textContent=msg;}
function refresh(){const done=queue.filter(i=>i.blob).length;$('count').textContent=queue.length+' 枚';$('start').disabled=busy||!queue.some(i=>!i.blob);$('zip').disabled=busy||!done;$('clear').disabled=busy||!queue.length;$('cancel').hidden=!busy;$('format').disabled=busy;$('quality').disabled=busy;$('pick').disabled=busy;$('files').disabled=busy;$('progress').value=queue.length?queue.filter(i=>i.state==='done'||i.state==='error').length/queue.length:0;}
function add(files){if(busy)return;let ignored=0;for(const file of files){if(!/\.(heic|heif|hif)$/i.test(file.name)){ignored++;continue;}if(file.size>100*1048576){ignored++;continue;}const item={file,state:'waiting',blob:null,url:null};const row=document.createElement('article');row.className='row';const img=document.createElement('img');img.alt='変換後のプレビュー';img.hidden=true;const info=document.createElement('div');info.className='info';const name=document.createElement('strong');name.textContent=file.name;const meta=document.createElement('small');meta.textContent=size(file.size)+' · 待機中';info.append(name,meta);const save=document.createElement('button');save.className='secondary';save.textContent='保存';save.disabled=true;save.onclick=()=>download(item.blob,item.output);row.append(img,info,save);$('list').append(row);Object.assign(item,{row,img,meta,save});queue.push(item);}announce(ignored?ignored+' 件は対象外または100 MB超のため追加できませんでした。':'写真を追加しました。「変換する」を押してください。');refresh();$('files').value='';}
function outputName(original,extension,used){const base=original.replace(/\.[^.]+$/,'').replace(/[<>:"/\\|?*\x00-\x1f]/g,'_').replace(/[. ]+$/,'')||'photo';let name=base+'.'+extension,n=2;while(used.has(name.toLowerCase()))name=base+'_'+n+++'.'+extension;used.add(name.toLowerCase());return name;}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function convert(item,type,quality){return new Promise(async(resolve,reject)=>{let worker,workerURL,timer;const clean=()=>{clearTimeout(timer);worker?.terminate();if(workerURL)URL.revokeObjectURL(workerURL);activeWorker=null;activeReject=null;};try{const buffer=await item.file.arrayBuffer();if(stop){reject(new Error('中止しました'));return;}workerURL=URL.createObjectURL(new Blob([$('decoder').textContent,'\n',$('worker').textContent],{type:'text/javascript'}));worker=new Worker(workerURL);activeWorker=worker;activeReject=()=>{clean();reject(new Error('中止しました'));};timer=setTimeout(()=>{clean();reject(new Error('処理が3分を超えました。別の写真でお試しください。'));},180000);worker.onmessage=({data})=>{clean();data.error?reject(new Error(data.error)):resolve(data);};worker.onerror=e=>{clean();reject(new Error('変換処理を起動できませんでした。EdgeまたはChromeで開いてください。'));};worker.postMessage({buffer,type,quality},[buffer]);}catch(e){clean();reject(e);}});}
$('pick').onclick=()=>$('files').click();$('files').onchange=e=>add(e.target.files);const drop=$('drop');drop.ondragover=e=>{e.preventDefault();if(!busy)drop.classList.add('hover');};drop.ondragleave=()=>drop.classList.remove('hover');drop.ondrop=e=>{e.preventDefault();drop.classList.remove('hover');add(e.dataTransfer.files);};window.addEventListener('dragover',e=>e.preventDefault());window.addEventListener('drop',e=>e.preventDefault());
$('quality').oninput=()=>$('qualityValue').textContent=$('quality').value+'%';$('format').onchange=()=>{$('qualityBox').hidden=$('format').value==='image/png';};
$('start').onclick=async()=>{busy=true;stop=false;const type=$('format').value,quality=Number($('quality').value)/100,extension=type==='image/png'?'png':'jpg';const used=new Set(queue.filter(i=>i.blob).map(i=>i.output.toLowerCase()));refresh();let index=0;for(const item of queue){index++;if(item.blob)continue;if(stop)break;item.state='working';item.row.classList.add('working');item.meta.textContent='変換中…';announce(index+' / '+queue.length+' 枚を変換中');try{const result=await convert(item,type,quality);item.blob=result.blob;item.output=outputName(item.file.name,extension,used);item.url=URL.createObjectURL(item.blob);item.img.src=item.url;item.img.hidden=false;item.save.disabled=false;item.state='done';item.meta.textContent=result.width+' × '+result.height+' · '+size(item.blob.size)+' · '+extension.toUpperCase()+(result.count>1?' · 主画像のみ':'');}catch(e){if(stop){item.state='waiting';item.meta.textContent='待機中';}else{item.state='error';item.meta.textContent=e.message;}}item.row.classList.remove('working');refresh();}busy=false;const errors=queue.filter(i=>i.state==='error').length;announce(stop?'中止しました。変換済みの写真は保存できます。':'変換完了：'+queue.filter(i=>i.blob).length+' 枚'+(errors?' ／ 失敗：'+errors+' 枚（再実行できます）':''));refresh();};
$('cancel').onclick=()=>{stop=true;activeReject?.();};$('clear').onclick=()=>{queue.forEach(i=>i.url&&URL.revokeObjectURL(i.url));queue.length=0;$('list').replaceChildren();announce('写真を選択してください。');refresh();};
$('zip').onclick=async()=>{busy=true;refresh();$('cancel').hidden=true;announce('ZIPを準備中…');try{const files={};for(const i of queue.filter(i=>i.blob))files[i.output]=new Uint8Array(await i.blob.arrayBuffer());const zip=await new Promise((resolve,reject)=>fflate.zip(files,{level:0},(error,data)=>error?reject(error):resolve(data)));download(new Blob([zip],{type:'application/zip'}),'converted_photos.zip');announce('ZIPを保存しました。ブラウザーのダウンロード先をご確認ください。');}catch(e){announce('ZIP作成に失敗しました。枚数を減らすか、個別に保存してください。');}busy=false;refresh();};refresh();
